# Generated by Django 3.2.4 on 2021-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('move1', models.CharField(max_length=100)),
                ('move2', models.CharField(max_length=100)),
                ('move3', models.CharField(max_length=100)),
                ('move4', models.CharField(max_length=100)),
                ('HP', models.IntegerField()),
                ('ATK', models.IntegerField()),
                ('DEF', models.IntegerField()),
                ('ACC', models.IntegerField()),
                ('EVA', models.IntegerField()),
                ('SPD', models.IntegerField()),
            ],
        ),
    ]
